version: '3.8'

services:
  whisper-diarization:
    build: .
    container_name: whisper-diarization-service
    ports:
      - "80:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false
      - WHISPER_MODEL=medium.en
      - WHISPER_DEVICE=auto
      - NEMO_DEVICE=auto
      - LOG_LEVEL=INFO
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./models:/app/models
    depends_on:
      - redis
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  redis:
    image: redis:7-alpine
    container_name: whisper-diarization-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped



volumes:
  redis_data:
