version: '3.8'

services:
  asr-whisper:
    build: .
    container_name: asr-whisper-ml
    ports:
      - "80:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./logs:/app/logs
      - ./cache:/app/cache
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app
      - PYTORCH_HOME=/app/models
      - HF_HOME=/app/models
      - CUDA_VISIBLE_DEVICES=0  # Set to empty string for CPU-only
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - asr-network

  # Optional: Redis for caching and job queuing
  redis:
    image: redis:7-alpine
    container_name: asr-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - asr-network

volumes:
  redis_data:

networks:
  asr-network:
    driver: bridge
