# NeMo MSDD (Multi-Speaker Diarization Detection) Configuration
# This configuration is optimized for production use with enhanced speaker diarization

name: "MSDDDiarizer"

# General settings
num_workers: 4
sample_rate: 16000
batch_size: 32
device: "auto"  # auto, cuda, cpu
verbose: true

# Diarization pipeline configuration
diarizer:
  manifest_filepath: null  # Will be set dynamically
  out_dir: null  # Will be set dynamically
  oracle_vad: false
  collar: 0.25
  ignore_overlap: true

  # Voice Activity Detection (VAD)
  vad:
    model_path: "vad_multilingual_marblenet"
    external_vad_manifest: null
    
    parameters:
      window_length_in_sec: 0.63
      shift_length_in_sec: 0.08
      smoothing: false
      overlap: 0.5
      onset: 0.5
      offset: 0.3
      pad_onset: 0.2
      pad_offset: 0.2
      min_duration_on: 0.5
      min_duration_off: 0.5
      filter_speech_first: true

  # Speaker Embedding Extraction
  speaker_embeddings:
    model_path: "titanet_large"
    parameters:
      window_length_in_sec: [1.9, 1.2, 0.5]
      shift_length_in_sec: [0.95, 0.6, 0.25]
      multiscale_weights: [1, 1, 1]
      save_embeddings: true
      normalize_embeddings: true

  # Clustering Configuration
  clustering:
    parameters:
      oracle_num_speakers: false
      max_num_speakers: 10
      enhanced_count_thres: 80
      max_rp_threshold: 0.25
      sparse_search_volume: 10
      maj_vote_spk_count: false
      chunk_cluster_count: 50
      embeddings_per_chunk: 10000
      clustering_method: "spectral"  # spectral, agglomerative, kmeans
      min_clusters: 2
      max_clusters: 10

  # MSDD Model Configuration
  msdd_model:
    model_path: null  # Will be set to pretrained model
    parameters:
      use_speaker_model_from_ckpt: true
      infer_batch_size: 25
      sigmoid_threshold: [0.7, 0.8, 0.9]
      seq_eval_mode: false
      split_infer: true
      diar_window_length: 50
      overlap_infer_spk_limit: 5
      use_adaptive_threshold: true
      adaptive_threshold_alpha: 0.1
      min_speaker_duration: 0.5
      max_speaker_duration: 30.0

  # ASR Configuration (optional)
  asr:
    model_path: null
    parameters:
      asr_based_vad: false
      asr_based_vad_threshold: 1.0
      asr_batch_size: null
      decoder_delay_in_sec: null
      word_ts_anchor_offset: null
      word_ts_anchor_pos: "start"
      fix_word_ts_with_VAD: false
      colored_text: true
      print_time: true
      break_lines: false

    # CTC Decoder Parameters
    ctc_decoder_parameters:
      pretrained_language_model: null
      beam_width: 32
      alpha: 0.5
      beta: 2.5

    # Realigning LM Parameters
    realigning_lm_parameters:
      arpa_language_model: null
      min_number_of_words: 3
      max_number_of_words: 10
      logprob_diff_threshold: 1.2

# Advanced MSDD Settings
msdd_advanced:
  # Speaker verification
  speaker_verification:
    enabled: true
    threshold: 0.5
    min_speaker_confidence: 0.7
  
  # Overlap detection
  overlap_detection:
    enabled: true
    min_overlap_duration: 0.1
    max_overlap_duration: 5.0
  
  # Temporal consistency
  temporal_consistency:
    enabled: true
    window_size: 10.0
    min_segment_duration: 0.5
  
  # Multi-scale processing
  multiscale:
    enabled: true
    scales: [0.5, 1.0, 2.0]
    weights: [0.3, 0.4, 0.3]

# Performance Optimization
performance:
  # Memory management
  max_memory_usage: "8GB"
  enable_mixed_precision: true
  
  # Parallel processing
  num_parallel_workers: 4
  enable_async_processing: true
  
  # Caching
  enable_embedding_cache: true
  cache_dir: "./cache"
  max_cache_size: "2GB"

# Output Configuration
output:
  formats: ["rttm", "json", "srt", "vtt"]
  include_confidence: true
  include_embeddings: false
  include_vad: true
  include_speaker_info: true
  
  # RTTM output
  rttm:
    include_speaker_names: true
    include_confidence: true
  
  # JSON output
  json:
    pretty_print: true
    include_metadata: true
    include_processing_info: true

